version: '3'

services:
  app:
    build: .
    entrypoint: sh -c ".docker/entrypoint.sh && npm run dev"
    volumes:
      - .:/home/node/app
    ports:
      - 3000:3000
  storybook:
    build: .
    entrypoint: sh -c "npm run storybook"
    depends_on:
      - app
    volumes: 
      - .:/home/node/app
    ports:
      - 6006:6006
