name: Development Integration

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Validate pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run lint
      - run: npm run test
