name: Development CI

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - run: npm ci
      - run: npm run test
