name: Development Integration

on:
  pull_request:
    branches:
      - development

jobs:
  test:
    name: Test pull request
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Setup Node
      - uses: actions/setup-node@v2.5.1
        with:
          node-version: 14
      - name: Install deps
      - run: npm install
      - name: Run lint
      - run: npm run lint
      - name: Run tests
      - run: npm run test
